#environment
ROOTFS=${EDGE_COMMON_SW_PATH}/rootfs.ext4
IMAGE=${EDGE_COMMON_SW_PATH}/Image
SYSROOT = ${SYSROOT_PATH}/sysroots/cortexa72-cortexa53-xilinx-linux
SDKTARGETSYSROOT = ${SYSROOT}
BASE_PLATFORM ?= ${PLATFORM_REPO_PATHS}/xilinx_vck190_base_202320_1/xilinx_vck190_base_202320_1.xpfm
SHELL := /bin/bash
.SHELLFLAGS := -e -o pipefail -c

# Makefile input options
TARGET ?= hw
PYTHON ?= python
BOARD_DATA_DIR ?= ./board_data
BOARD_DATA_KIND ?= random
BOARD_DATA_SEED ?= 0
BOARD_DATA_FLAGS ?=

LANES := {{ lanes }}
GRID_DEPTH := {{ grid_depth }}
DATA_ITER := {{ data_iter }}

XO_DIR=./$(TARGET).xo_dir
XSA_DIR=./$(TARGET).xsa_dir
PACKAGE_DIR = ./$(TARGET).xclbin_dir

# File names and locations
KERNEL := TopPL
KERNEL_SRC := ./pl/$(KERNEL).cpp
KERNEL_XO := ./pl/$(KERNEL).xo

XSA := ./$(XSA_DIR)/svd.xsa
HOST_SRC = ./ps/host.cpp
HOST = host.exe
XCLBIN = ./$(PACKAGE_DIR)/svd.xclbin
GRAPH := ./aie/TopGraph.cpp
GRAPH_DEPS := $(GRAPH) \
	./aie/TopGraph.h \
	./aie/Config.h \
	./aie/ProcessGraph/StencilCoreGraph.h \
	./aie/ProcessGraph/StencilCoreGraph.cpp \
	./aie/ProcessUnit/include.h \
	./aie/ProcessUnit/hdiff.h \
	./aie/ProcessUnit/hdiff_lap.cc \
	./aie/ProcessUnit/hdiff_flux1.cc \
	./aie/ProcessUnit/hdiff_flux2.cc

GRAPH_O := libadf.a
CONFIG_FILE := conn.cfg

VPP := v++
AIECC := v++ -c --mode aie
AIESIM := aiesimulator
X86SIM := x86simulator

HW_EMU_CMD := ./launch_hw_emu.sh -g
AIE_FREQ = --freqhz=450000000

AIE_INCLUDE_FLAGS := --include "$(XILINX_VITIS)/aietools/include" --include "./aie" --include "./"
AIE_STRATEGY := --aie.xlopt=0 --aie.runtime-opt --aie.verbose --aie.Xchess=main:backend.mist2.xargs=-ggraph
AIE_FLAGS := $(AIE_INCLUDE_FLAGS) $(AIE_STRATEGY) --platform $(BASE_PLATFORM) --work_dir ./Work
AIE_FLAGS += $(AIE_FREQ)

ifeq ($(TARGET),sw_emu)
	AIE_FLAGS += --target x86sim
else
	AIE_FLAGS += --target hw
endif

VPP_XO_FLAGS := -c -t $(TARGET) --platform $(BASE_PLATFORM) -k $(KERNEL) --save-temps -g

VPP_LINK_FLAGS := -l -t $(TARGET) --platform $(BASE_PLATFORM) $(GRAPH_O) $(KERNEL_XO) --save-temps -g --config $(CONFIG_FILE) -o $(XSA)
VPP_LINK_FLAGS += --vivado.impl.jobs 256

CXX := $(XILINX_VITIS)/gnu/aarch64/lin/aarch64-linux/bin/aarch64-linux-gnu-g++

GCC_FLAGS := -Wall -c \
	     	 -std=c++20 \
			 -Wno-int-to-pointer-cast \
			 -pthread \
			 --sysroot=$(SYSROOT)

GCC_INCLUDES := -I$(SYSROOT)/usr/include/xrt \
				-I./  \
				-I${XILINX_VITIS}/aietools/include \
				-I${XILINX_VITIS}/include \
				-I${XILINX_HLS}/include \
				-I./aie

GCC_LIB := -lxaiengine -ladf_api_xrt -lxrt_core -lxrt_coreutil \
		   -pthread \
		   -L$(SYSROOT)/usr/lib \
		   --sysroot=$(SYSROOT) \
		   -L${XILINX_VITIS}/aietools/lib/aarch64.o

.ONESHELL:
.PHONY: clean all board_data sim_data kernels aie sim xsa host package run_emu clear_board_data

all: board_data aie kernels xsa host package
sd_card: all

board_data:
	mkdir -p $(BOARD_DATA_DIR)
	rm -f $(BOARD_DATA_DIR)/input_plio*.txt $(BOARD_DATA_DIR)/lane_map.txt
	rm -f $(BOARD_DATA_DIR)/input.txt $(BOARD_DATA_DIR)/gold_out.txt
	rm -f $(BOARD_DATA_DIR)/hdiff_plane*.txt $(BOARD_DATA_DIR)/hdiff_input_stream.txt
	$(PYTHON) ./data/gen_case.py --minimal --emit-input-matrix --skip-lane-plio --data-dir $(BOARD_DATA_DIR) \
		--lanes $(LANES) --depth $(GRID_DEPTH) --iter $(DATA_ITER) \
		--kind $(BOARD_DATA_KIND) --seed $(BOARD_DATA_SEED) $(BOARD_DATA_FLAGS)
	@echo "COMPLETE: board input data created in $(BOARD_DATA_DIR)."

sim_data:
	mkdir -p ./data
	rm -f ./data/input_plio*.txt ./data/lane_map.txt
	rm -f ./data/input.txt ./data/gold_out.txt
	rm -f ./data/hdiff_plane*.txt ./data/hdiff_input_stream.txt
	$(PYTHON) ./data/gen_case.py --data-dir ./data \
		--lanes $(LANES) --depth $(GRID_DEPTH) --iter $(DATA_ITER) \
		--kind $(BOARD_DATA_KIND) --seed $(BOARD_DATA_SEED) $(BOARD_DATA_FLAGS)
	@echo "COMPLETE: AIE sim data created in ./data."

kernels: $(KERNEL_XO)

$(KERNEL_XO): $(KERNEL_SRC) ./aie/Config.h ./aie/ProcessUnit/include.h
	mkdir -p $(XO_DIR)
	$(VPP) $(VPP_XO_FLAGS) -o $(KERNEL_XO) $(KERNEL_SRC) | tee $(XO_DIR)/$(KERNEL).log

aie: $(GRAPH_O)

sim: sim_data $(GRAPH_O)
ifeq ($(TARGET),sw_emu)
	$(X86SIM) --pkg-dir=./Work --online -wdb
else
	$(AIESIM) --pkg-dir=./Work --online -wdb --profile
endif

$(GRAPH_O): $(GRAPH_DEPS)
	$(AIECC) $(AIE_FLAGS) $(GRAPH)

xsa: $(XSA)
$(XSA): $(GRAPH_O) $(KERNEL_XO) $(CONFIG_FILE) Makefile
	mkdir -p $(XSA_DIR)
	$(VPP) $(VPP_LINK_FLAGS) || (echo "task: [xsa] failed error code: $$?"; exit 1)
	@echo "COMPLETE: .xsa created."

host:
	$(CXX) $(GCC_FLAGS) $(GCC_INCLUDES) -c $(HOST_SRC) -o host.o
	$(CXX) $(GCC_FLAGS) $(GCC_INCLUDES) -c ./Work/ps/c_rts/aie_control_xrt.cpp -o aie_control_xrt.o
	$(CXX) host.o aie_control_xrt.o $(GRAPH_O) $(GCC_LIB) -std=c++20 -o $(HOST)
	@echo "COMPLETE: Host application created."

package: $(XCLBIN)
$(XCLBIN): board_data $(XSA) $(GRAPH_O) $(KERNEL_XO) $(HOST) run.sh xrt.ini Makefile
	mkdir -p $(PACKAGE_DIR)
	v++ -p -t ${TARGET} \
		-f ${BASE_PLATFORM} \
		--package.out_dir=$(PACKAGE_DIR) \
		--package.rootfs=${ROOTFS} \
		--package.image_format=ext4 \
		--package.boot_mode=sd \
		--package.kernel_image=${IMAGE} \
		--package.defer_aie_run \
		--package.sd_file $(HOST) \
		--package.sd_file run.sh \
		--package.sd_file xrt.ini \
		--package.sd_dir $(BOARD_DATA_DIR) \
		$(XSA) $(GRAPH_O) -o $(XCLBIN)
	@echo "COMPLETE: package created."

run: all run_emu

run_emu:
ifeq (${TARGET},hw_emu)
	cd ./$(PACKAGE_DIR)
	$(HW_EMU_CMD)
else
	@echo "Hardware build, no emulation executed."
endif

clear_aie:
	rm -rf Work *.a
clear_pl:
	rm -rf $(XO_DIR) pl/*.xo
clear_ps:
	rm -rf *.o *.exe
clear_xsa:
	rm -rf $(XSA_DIR)
clear_package:
	rm -rf $(PACKAGE_DIR)
clear_board_data:
	rm -rf $(BOARD_DATA_DIR) ./data/input_plio*.txt ./data/lane_map.txt ./data/input.txt ./data/gold_out.txt
clear_all: clear_aie clear_pl clear_ps clear_xsa clear_package clear_board_data
	rm -rf hls TopPL logs
	rm -rf _x v++* .Xil *.db *.log *.wcfg *.wdb pl_sample_counts *.csv .AIE_* ISS_* aiesimulator_* function_*
