ROOT_DIR := ..

.PHONY: all aie sim xsa host package run clean clear_aie clear_pl clear_ps clear_xsa clear_package clear_all

all aie sim xsa host package run clean clear_aie clear_pl clear_ps clear_xsa clear_package clear_all:
	$(MAKE) -C $(ROOT_DIR) $@
